### ISSUE TITLE
Game datasets used in the paper?

### ISSUE THREAD

**Issue by XiSHEN0220** [dmsm/MarioNette#1]
Hi, Dmitriy, 

Congrats on the nice work !!! 
Could you share the game datasets used in the paper? _(Fighting Hero (one level, 5,330 frames); Nintendo Super Mario Bros. (one level, 2,220 frames) and ATARI Space Invaders (5,000 frames))_

Best, 

Xi

**Comment by dmsm** [comment]
Thanks for your interest! For Fighting Hero and Mario, we used frames from public YouTube gameplay videos. For Space Invaders, we used the ATARI dataset found here: https://github.com/zhixuan-lin/SPACE

**Comment by XiSHEN0220** [comment]
Thanks a lot~
