### ISSUE TITLE
Guidance with SpaceInvaders

### ISSUE THREAD

**Issue by ThomasRot** [dmsm/MarioNette#2]
Hi folks,

I trained MarioNette with a data set of 2^15 128x128 scenes of SpaceInvaders, but only the background is reconstructed. Do you have some ideas, about which kind of parameters I should modify to reach the results described in the paper? 

![image](https://user-images.githubusercontent.com/17272419/170813673-3b1f6036-3c71-4b97-bfc7-4e34367bed5d.png)

![image](https://user-images.githubusercontent.com/17272419/170813688-28901c72-cc76-4862-8e1a-9e6a3e374a6b.png)

Thanks a lot for your insights!

**Comment by dmsm** [comment]
Thanks for your interest! What parameters are you using to run the training script? In particular, you want anchor grid resolution to be such that each patch roughly fits a single sprite. Passing in `--layer_size 16` should be a reasonable choice. Let me know if this helps.

**Comment by ThomasRot** [comment]
Thanks for your answer, I'll try around with that. Are the used hyperparameters for each experiment in the paper documented somewhere? I can't seem to find them.

**Comment by dmsm** [comment]
Yes, all hyperparameters are specified in the paper. In particular, Section 3.2 states that patch size `k = 16` is used for Mario, whereas `k = 32` is used for Space Invaders. Note that `k = canvas_size / layer_size`.

**Comment by ThomasRot** [comment]
Thanks a lot. I had some success with `num_layers = 2`, `num_classes = 54` (following the image of the dictionary in the paper only) and `layer_size = 16` (like written two comments above, though  `k{32} = canvas_size{128} / layer_size` would imply `layer_size = 4` if I'm not mistaken, but that did not work that well)
